version: '2'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "8082:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './db-data'
